## HCI 570X Data Self Portait

### Part One Brief
Create a simple "Self Portrait Database" for your Project 01 concept. Create a database that represents yourself in one of two ways: 

 Create a database from physical objects:
- Gather one type of object or multiple types of objects that represent you (i.e. receipts, collections of diff. objects, shoes, etc)
- Photograph them with your phone/camera -or- digitize them using a camera
Create a database from your digital life or think about what digital objects you can collect like text messages.
- Download the data -or- create an Excel spreadsheet with your data
- Represent this data visually by placing the data in a Illustrator or Word document.

### Part One - My Idea
- My idea is to create a database of my financial transactions for the last 2 years (this is how far back I can go with my providers) and classifying them based on some basic categories such as FOOD, ENTERTAINMENT, AUTO, and so on.  They will include the date, a description or name of the payee, and of course the $ amount.
- I want to explore different ways of visualizing this data that could show my spending/earning history in unique ways and/or create an artistic statement. It might be interesting to juxtapose it with some other per day information that I can get from the web such has news headlines, tweets, weather, etc., an idea inspired by researching *Zero Noon* by Rafael Lozano-Hemmer during in our class readings https://www.lozano-hemmer.com/zero_noon.php

### Data Procurement
I started by first logging into my online banking site and seeing what data was available.  They provided recent transactions and some basic search but it did not appear to be downloadable.  I next visited my bank in person and was told that they could retrieve the data for me for a $40 research fee.  I agreed to this and then waited a day for the files to be delivered.  Unfortunately, the transaction history was just images of my statements rendered into PDFs making the text unselectable or able to be processed in any efficient way. I investigated a couple free OCR solutions which also did not work well. I considered hand entering the transactions into a spreadsheet but that looked like it would take a lot of time and be error prone.  I returned to the online app and did some more digging and eventually did find a way to export transaction history but it is limited to the last 2 years.  I decided that 2 years of data would be sufficient to create something interesting.

Next I went to my primary credit card's online application and downloaded all of my credit card transactions for the same time period.  These transactions included basic categories so I decided to use these and apply them to my bank transactions.

### Use pandas to explore and manipulate/clean the data
#### Credit History

In [ ]:
import pandas as pd

credit = pd.read_csv('Chase6684_Activity20210913_20230913_20230913.CSV')
display(credit)
print("Columns")
for name in credit.columns.tolist():
    print(name)

#figure out the categories that Chase bank has used
categories = []
for i, row in credit.iterrows():
    cat = str(row["Category"])
    if cat not in categories:
        categories.append(cat)

print(f"\n{len(categories)} Categories")
for cat in categories:
    print(cat)

These categories look good and should allow for interesting options for visualization, emotion, etc. 

What the heck is "nan"? I visually looked at the CSV and nan is for credit card payments which are not categorized.

> 10/05/2021,10/05/2021,AUTOMATIC PAYMENT - THANK,,Payment,1270.20,

I will categorize these as **Payment**

In [ ]:
amount = 0
count = 0
for i, row in credit.iterrows():
    if str(row["Category"]) == 'nan':
        count += 1
        amount += row["Amount"]
        #Set it to Payment
        row["Category"] = "Payment"
        #display(row)
        credit.iloc[i] = row
        

print(f"Eeeek, I spent ${amount} in 2 years over {count} payments")

#Save the updated data file
from pathlib import Path  
filepath = Path('transformed/credit.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
credit.to_csv(filepath)

### Other Insights

In [ ]:
print(f"I spent ${abs(credit[credit['Description'].str.contains('AMZN')]['Amount'].sum())} at Amazon.com")

In [ ]:
total = 0
for cat in categories:
    amount = abs(credit[credit['Category'] == cat]['Amount'].sum())
    total += amount
    print(f"{cat}: ${amount:,.2f}")

print(f"I charged ${total:,.2f} in 2021/2023")

#### Banking History
- Account Name : FIRST POINT CHECKING
- Account Number : xxx420
- Date Range : 09/13/2021-09/13/2023

In [ ]:
import pandas as pd

bank = pd.read_csv('FNB_Activity20210913_20230913_20230913.CSV')
display(bank)
print("Columns")
for name in bank.columns.tolist():
    print(name)

This data is a little more cryptic and does not contain a category. I will transform the rows to include a new column for category and try to auto populate the value based on personal knowledge of the expenses.  For example, HY VEE would be **Groceries**, CULVERS is **Food & Drink**

In [11]:
#print(len(bank.index))

# Food & Drink
# Entertainment
# Bills & Utilities
# Health & Wellness
# nan
# Shopping
# Gas
# Groceries
# Professional Services
# Home
# Travel
# Education
# Automotive
# Personal
# Gifts & Donations

bank['Category'] = ['']*(len(bank.index))
#Categorize
for i, row in bank.iterrows():
    for g in ["WAL-MART",
              "HY VEE",
              "HY-VEE",
              "SAFEWAY",
              "WHEATSFIELD",
              "ALDI",
              "TRADER JOE",
              "PAMMEL GROCERY",
              "SAMSCLUB",
              "FAREWAY",
              "SUNSHINE",
              "WALGREENS"]:
        if g in row["Description"].upper():
            row["Category"] = "Groceries"

    if row["Category"] == "":
        for g in ["PERFECT GAMES",
                "SQ *ACPS",
                "80/35",
                "NORTH GRAND",
                "BIG CREEK",
                "XBK DES MOINES",
                "CINEMARK"]:
            if g in row["Description"].upper():
                row["Category"] = "Entertainment"

    if row["Category"] == "":
        for g in [
            "MCDONALD'S",
            "B BOPS",
            "PHO",
            "JAVA JOES",
            "AUNT MAUDES",
            "FLAME-N-SKEWER",
            "131 WELCH AVE",
            "THE CAFE",
            "AJ S LIQUOR",
            "FIVE GUYS",
            "ROASTERIE",
            "BOULDER",
            "OASIS FALAFE",
            "SPICE",
            "PURCHASE AT SQ",
            "LOTF_1",
            "SQ *1+1",
            "CULVERS",
            "DESIGN CAFE",
            "ARBY S",
            "LOCKWOOD",
            "TAZA",
            "SUBWAY",
            "CHARRO BAR",
            "VILLAGE INN",
            "STARBUCKS",
            "WHISKEY RIVER",
            "SARKU",
            "EL AZTECA",
            "JERSEY MIKES",
            "CAFE DIEM",
            "BURGER KING",
            "MUCKY DUCK",
            "SPORTSMANS",
            "KWIK STOP LIQUOR",
            'WOK N ROLL',
            "LA CASA MAYA",
            "CYCLONE L",
            "JIMMY JOHNS",
            "TACO BELL",
            "SBARRO",
            "BLAZE PIZZA",
            "CAFEBEAUDELAIRE",
            "ABERLARDOSMEXICA",
            "BURGIE",
            "DOUGH CO",
            "CORNBRED",
            "ALLUVIAL",
            "DAYTIME",
            "TROPICAL SMOOTHI",
            "LONDON UNDER",
            "ABERLARDOSMEXICA",
            "THE ANGRY IR"]:
            if g in row["Description"].upper():
                row["Category"] = "Food & Drink"

    if row["Category"] == "":
        for g in ["CITY OF AMES UT BILL",
                "ALLIANT - IPL",
                "COUNTY TREASURER VEHICLE",
                "CHASE CREDIT CRD AUTOPAY",
                "ASPEN WASTE",
                "VERIZON WIRELESS",
                "DHS CSRU"]:
            if g in row["Description"].upper():
                row["Category"] = "Bills & Utilities"

    if row["Category"] == "":
        for g in ["CASEYS", "PHILLIPS 66", "SWIFT STOP", "KUMGO", "KUM&GO", "SOUTH GATE", "QT", "RUTHVEN"]:
            if g in row["Description"].upper():
                row["Category"] = "Gas"

    if row["Category"] == "":
        for g in ["O DONNELL ACE HA",
                "GOODWILL",
                "OVERFLOW",
                "LOWE'S",
                "MNRD",
                "HABITAT FOR HUMAN",
                "IBMC ACH PMTS",
                "IOWA BANKERS MTG ACH",
                "HABITAT FOR HUMA",
                "COUNTY TREASURER TAX",
                "SALVATION AR",
                "JCPENNEY"]:
            if g in row["Description"].upper():
                row["Category"] = "Home"

    if row["Category"] == "":
        for g in ["T J MAXX", "TARGET", "LOFT", "WILLIAMS-SONOMA", "ISU SURPLUS", "SUPERCENTER", "FABRIC"]:
            if g in row["Description"].upper():
                row["Category"] = "Shopping"

    if row["Category"] == "":
        for g in ["ATM WITHDRAWAL",
            "TRANSFER TO ",
            "HEROIC",
            "DEBIT",
            "TAX",
            "FEE",
            "SAFE DEPOSIT BOX",
            "RIEMAN MUSIC",
            "VENMO PAYMENT"]:
            if g in row["Description"].upper():
                row["Category"] = "Personal"

    if row["Category"] == "":
        for g in ["NEW YORK NY",
                "MINNEAPOLIS",
                "SAINT PAUL",
                "DES MOINES AIRPO",
                " MN ", " CA ", " CO ", " IL ", " KY ", " OR ", " NV ", " WA ",
                "CEDAR RAPIDS"]:
            if g in row["Description"].upper():
                row["Category"] = "Travel"

    if row["Category"] == "":
        for g in ["PLANET FIT", "MCFARLAND"]:
            if g in row["Description"].upper():
                row["Category"] = "Health & Wellness"

    if row["Category"] == "":
        for g in ["IOWA STATE UNIV. ACH PYMT"]:
            if g in row["Description"].upper():
                row["Category"] = "Education"

    if row["Category"] == "":
        for g in ["FARMERS INS", "SUPER SHINE", "JIFFY LUBE", "ADVANCE AUTO", "GATEWAYEXPRESS", "WILD WATER", "DOT"]:
            if g in row["Description"].upper():
                row["Category"] = "Automotive"

    if row["Category"] == "":
        for g in ["DONNELLEY",
                "IASTTAXRFD",
                "DEPOSIT",
                "PAYMENT",
                "CHECK DEPOSIT",
                "CHECK",
                "TRANSFER",
                "INTEREST",
                "PAYPAL TRANSFER",
                "IRS TREAS",
                "PAYROLL",
                "THE HARTFORD"]:
            if g in row["Description"].upper():
                row["Category"] = "Deposit"

    bank.iloc[i] = row

print(f"There are still {len(bank[bank['Category'] == ''])} uncategorized transactions.")
#display(bank[bank['Category'] == ''])
#Save the updated data file
from pathlib import Path  
filepath = Path('transformed/bank.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
bank.to_csv(filepath) 
display(bank)

There are still 0 uncategorized transactions.

,Transaction Number,Date,Description,Memo,Amount Debit,Amount Credit,Balance,Check Number,Fees,Category
0,20230912000000[-6:CST]*2.05*501**Interest paid,09/12/2023,Interest paid,NaN,NaN,2.05,25279.23,NaN,0.0,Deposit
1,20230912000000[-6:CST]*-7.78*0**XX3498 POS WIT...,09/12/2023,XX3498 POS WITHDRAWAL. SHELL SERVICE S B URLIN...,NaN,-7.78,NaN,25277.18,NaN,0.0,Travel
2,20230912000000[-6:CST]*-4.25*0**XX3498 POS PUR...,09/12/2023,XX3498 POS PURCHASE AT PARKING METER - S ANTA ...,NaN,-4.25,NaN,25284.96,NaN,0.0,Travel
3,20230911000000[-6:CST]*-38.52*0**XX3498 POS WI...,09/11/2023,XX3498 POS WITHDRAWAL. WHOLEFDS 20955 CU PERTI...,NaN,-38.52,NaN,25289.21,NaN,0.0,Travel
4,20230911000000[-6:CST]*-19.22*0**XX3498 POS WI...,09/11/2023,XX3498 POS WITHDRAWAL. COMMON SAGE SAN F RANCI...,NaN,-19.22,NaN,25327.73,NaN,0.0,Travel
...,...,...,...,...,...,...,...,...,...,...
1126,20220314000000[-6:CST]*-223.10*0**Alliant - IP...,03/14/2022,Alliant - IPL PAYMENT 3836938783,NaN,-223.10,NaN,45716.65,NaN,0.0,Bills & Utilities
1127,20220314000000[-6:CST]*-24.00*0**XX3498 POS PU...,03/14/2022,XX3498 POS PURCHASE AT MILL CITY MUSEUM MINNEA...,NaN,-24.00,NaN,45939.75,NaN,0.0,Travel
1128,20220314000000[-6:CST]*-16.54*0**XX3498 POS PU...,03/14/2022,XX3498 POS PURCHASE AT OUTLET ST.PAUL CA MPUS ...,NaN,-16.54,NaN,45963.75,NaN,0.0,Travel
1129,20220314000000[-6:CST]*-14.01*0**XX3498 POS PU...,03/14/2022,XX3498 POS PURCHASE AT TST* Farmers Kitc hen &...,NaN,-14.01,NaN,45980.29,NaN,0.0,Travel
1130,20220314000000[-6:CST]*-12.24*0**XX3498 POS WI...,03/14/2022,XX3498 POS WITHDRAWAL. CASEYS GEN STORE ELLEND...,NaN,-12.24,NaN,45994.30,NaN,0.0,Gas

### Other Data

Other data ideas are news headlines, personal photos, top tweets, weather, etc.  I can use python to get the data and save to CSV or whatever the service provides.  Most allow you to pull data and export from their website.  This does not need to be real-time data.

#### Example Open Meteo

In [ ]:
import requests
from pprint import pprint

# import http.client as http_client
# import logging
# http_client.HTTPConnection.debuglevel = 1

# # You must initialize logging, otherwise you'll not see debug output.
# logging.basicConfig()
# logging.getLogger().setLevel(logging.DEBUG)
# requests_log = logging.getLogger("requests.packages.urllib3")
# requests_log.setLevel(logging.DEBUG)
# requests_log.propagate = True

start_date = "2021-09-13"
end_date = "2023-09-13"

url = f"https://archive-api.open-meteo.com/v1/archive?latitude=42.0347&longitude=-93.6199&start_date={start_date}&end_date={end_date}&hourly=rain&daily=temperature_2m_max,sunrise,sunset&temperature_unit=fahrenheit&windspeed_unit=mph&precipitation_unit=inch&timezone=America%2FChicago"

raw_response = requests.get(url) # make request to API

items_dict = raw_response.json() # convert json payload to python dictionary
display(items_dict) # print the dictionary nicely

### Google Photos

In [ ]:
%pip install google-api-core

In [ ]:
%pip install google-api-python-client
%pip install google-auth
%pip install google-auth-httplib2
%pip install google-auth-oauthlib
%pip install googleapis-common-protos

#### Google Auth
- https://developers.google.com/photos/library/guides/get-started
- https://medium.com/@najeem/analyzing-my-google-photos-library-with-python-and-pandas-bcb746c2d0f2
- https://stackoverflow.com/questions/66689941/google-photos-api-new-version
- https://sparkbyexamples.com/pandas/pandas-select-dataframe-rows-between-two-dates/
- https://developers.google.com/photos/library/guides/access-media-items#base-urls

In [ ]:
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/photoslibrary.readonly']

creds = None
# The file token.pickle stores the user's access and refresh tokens, and is
# created automatically when the authorization flow completes for the first
# time.
if os.path.exists('token.pickle'):
    with open('token.pickle', 'rb') as token:
        creds = pickle.load(token)
# If there are no (valid) credentials available, let the user log in.
if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file(
            'google-photos-credentials.json', SCOPES)
        creds = flow.run_local_server(port=0)
    # Save the credentials for the next run
    with open('token.pickle', 'wb') as token:
        pickle.dump(creds, token)

google_photos = build('photoslibrary', 'v1', credentials=creds, static_discovery=False)
print("Authenticated with Google Photos")

In [ ]:
photos = []
nextpagetoken = None
# The default number of media items to return at a time is 25. The maximum pageSize is 100.
while nextpagetoken != '':
    results = google_photos.mediaItems().list(pageSize=100, pageToken=nextpagetoken).execute()
    photos += results.get('mediaItems', [])
    print(f"Number of items processed:{len(photos)}", end='\r')
    nextpagetoken = results.get('nextPageToken', '')

print('\n')
print(f'Found {len(photos)} photos on Google Photos')

In [ ]:
import pandas as pd
# Convert the list of dict into a dataframe.
df = pd.DataFrame(photos)

# Taking the column mediaMetadata and splitting it into individual columns
dfmeta = df.mediaMetadata.apply(pd.Series)

# Combining all the different columns into one final dataframe
photo_data = pd.concat(
    [
        df.drop('mediaMetadata', axis=1), 
        dfmeta.drop('photo', axis=1), 
        dfmeta.photo.apply(pd.Series)
    ], axis=1
)

In [ ]:
print(photo_data.dtypes)

In [ ]:
# Convert the creation time to a datetime dtype
photo_data.creationTime = pd.to_datetime(photo_data.creationTime)

# Convert other numeric data into numeric dtypes
for c in ['width', 'height', 'apertureFNumber', 'focalLength', 'isoEquivalent']:
    photo_data[c] = pd.to_numeric(photo_data[c])
    
display(photo_data)

In [ ]:
from pathlib import Path  
filepath = Path('transformed/photos.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
photo_data.to_csv(filepath)

In [ ]:
%pip install matplotlib

In [ ]:
photo_data.mimeType.value_counts()

photo_data.groupby(photo_data.creationTime.dt.year).id.count().plot(kind='bar')

In [ ]:
photo_data.creationTime.dt.dayofweek.hist(bins=7)

In [ ]:
photo_data.creationTime.dt.hour.hist(bins=24)

In [ ]:
from IPython.display import Image
import requests

def display_image(id):
    img = google_photos.mediaItems().get(mediaItemId=id).execute()
    return Image(img['baseUrl'], format='png')

def save_image(info, currDate, filename):
    print(f'Saving photos/{currDate}/{filename}')
    w = 2048
    h = 1024

    if info['width'] > info['height']:
        w = 2048
        h = 1024
    else:
        w = 1024
        h = 2048

    pngImage = Image(info['baseUrl'] + f'=w{w}-h{h}-c-d', format='png')
    filepath = Path(f'photos/{currDate}/{filename}')  
    filepath.parent.mkdir(parents=True, exist_ok=True)  
    with open(filepath, 'wb') as f:
        f.write(pngImage.data)
        f.close()

start_date = '2021-09-13'
end_date = '2023-09-13'
mask = (photo_data['creationTime'] > start_date) & (photo_data['creationTime'] <= end_date)
subset = photo_data.loc[mask]

print(f"{len(subset)} in the date range")

processed = []
for i, row in subset.iterrows():
    currDate = row['creationTime'].strftime("%m-%d-%Y")
    if (currDate not in processed):
        filename = f"{currDate}-{row['id']}.png"
        save_image(row, currDate, filename)
        if len(os.listdir(f'photos/{currDate}')) > 6:
            processed.append(currDate)

In [ ]:
import os
from PIL import Image
from IPython.display import display

#logging.getLogger().setLevel(logging.INFO)

for file_path in os.listdir('photos'):
    display(file_path)
    for photoname in os.listdir(f'photos/{file_path}'):
        #display(photoname)
        img = Image.open(f'photos/{file_path}/{photoname}')
        display(img.resize((img.width // 10, img.height // 10)))